extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier

env:
  node: true

parserOptions:
  project:
    - tsconfig.eslint.json

rules:
  "@typescript-eslint/no-explicit-any": "off"
  "@typescript-eslint/explicit-module-boundary-types": "warn"
  "@typescript-eslint/no-non-null-assertion": "off"
  "@typescript-eslint/no-unused-vars":
    - "warn"
    - varsIgnorePattern: "^_"
      args: "none"
      ignoreRestSiblings: true

overrides:
  - files:
      - "src/**/*.ts"
