name: Test

on: push

jobs:
  example:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "npm"

      - run: npm ci

      - run: npm run example

      - run: test -z "$(git diff)"
